services:
  web:
    image: 'python:3.13-alpine'
    build:
      context: "https://github.com/andetazz/11webtiendamotos.git"
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    volumes:
      - '/2826869/andycompumotos:/app/app/static'

      